on:
  push:
    branches:
      - "main"

  pull_request:
    branches:
      - "main"

name: Build

jobs:
  create-boot-image:
    name: Create boot image for s3ve3g
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
      - name: Build Mu
        run: |
          sudo apt update
          chmod 744 ./setup_env.sh
          ./setup_env.sh -p apt
          chmod 744 ./build_uefi.sh
          ./build_uefi.sh -d s3ve3g
      - uses: actions/upload-artifact@v3
        with:
          name: Samsung Galaxy S3 Neo
          path: ./Mu-s3ve3g.img
